services:
  redis:
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - ./db/redis/data:/data
    restart: always